// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Mic.PhoneBook.DataLayer.Entities
{
    public partial class Phone
    {
        public int Id { get; set; }
        public string PersonName { get; set; }
        public string PhoneNumber { get; set; }
        public bool? Gender { get; set; }
    }
}